# DockerCompose
version: '3.3'

services:
   db:
     image: mariadb
     volumes:
       - ./mariadatabase:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: basededatos
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin
     ports:
      - "8889:3306"
