version: '3.3'

services:
    bd_mySql:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: PepitoElDeLosPalotes
    mongo:
        image: mongo:latest
        restart: always
        ports:
          - "27017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: pass
          
    mongo-express:
        image: mongo-express:latest
        restart: always
        ports:
          - "8081:8081"
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      
    tomcat:
        image: tomcat:latest
        ports:
          - "8055:8080"
        restart: always
        environment:
           CATALINA_BASE:   /usr/local/tomcat
           CATALINA_HOME:   /usr/local/tomcat
           CATALINA_TMPDIR: /usr/local/tomcat/temp
           JRE_HOME:        /usr
           CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
    
    apache:
        image: php:7-apache
        volumes:
          - ./data/:/var/www/html
        ports:
          - 80:80
          
    
    nginx: 
        image: nginx:latest
        container_name: production_nginx
        volumes:
            - db_data:/var/lib/nginx
        ports:
            - 81:80  
volumes:
    db_data: